/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medikart;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naman
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
        ArrayList<String> arst=new ArrayList<>();

ArrayList<JButton> ar = new ArrayList<>();
ArrayList<JPanel> jp= new ArrayList<>();
ArrayList<Integer> arst2 = new ArrayList<>();
int count1=0;
    public login() {
        initComponents();
        setSize(420, 350);
        jPasswordField1.setBounds(200, 150, 110, 30);
        //jPanel2.setBounds(150, 150, 360, 300);
        jTextField1.setBounds(200, 105, 110, 30);
        jLabel1.setBounds(80, 90, 90, 50);
        jLabel2.setBounds(80, 140, 90, 50);
        jButton1.setBounds(300, 200, 80, 30);
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        jPanel3.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
        jPanel5.setBackground(Color.WHITE);
        jPanel6.setBackground(Color.WHITE);
        
     
        jPanel2.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jLabel35.setVisible(false);
        jLabel36.setVisible(false);
        jLabel37.setVisible(false);
        jLabel38.setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 60, 119, 40);

        jLabel1.setBackground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 70, 60, 32);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(111, 62, 118, 32);

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 133, 60, 34);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(140, 110, 118, 34);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/delete-big.jpg"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 180, 70, 90);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/user_customer.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(220, 240, 100, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/add-notes.png"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 150, 130, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/20131021_update_ss_144176041.jpg"))); // NOI18N
        jButton5.setText("jButton5");
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 170, 80, 100);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Customer ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(22, 30, 142, 29);

        jTextField2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel2.add(jTextField2);
        jTextField2.setBounds(10, 50, 6, 35);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/search.jpg"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(25, 76, 275, 175);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 200, 0, 0);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 83, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 20, 83, 29);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 40, 83, 29);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 60, 83, 29);

        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 80, 34, 14);

        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(68, 0, 34, 14);

        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(72, 20, 40, 14);

        jLabel11.setText("jLabel11");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(52, 40, 40, 14);

        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(62, 60, 40, 14);

        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(52, 80, 40, 14);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/Assess.jpg"))); // NOI18N
        jButton7.setText("jButton7");
        jPanel3.add(jButton7);
        jButton7.setBounds(20, 20, 40, 295);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(270, 130, 0, 0);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setText("Customer ID");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(40, 20, 142, 29);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("Customer Name");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(40, 60, 182, 29);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("Phone");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(40, 90, 74, 29);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("Address");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(40, 140, 95, 29);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setText("Email");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(30, 180, 64, 29);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel4.add(jLabel19);
        jLabel19.setBounds(150, 20, 0, 0);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(130, 60, 0, 0);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel4.add(jLabel21);
        jLabel21.setBounds(150, 110, 0, 0);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel4.add(jLabel22);
        jLabel22.setBounds(130, 150, 0, 0);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel4.add(jLabel23);
        jLabel23.setBounds(130, 200, 0, 0);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(26);
        jTable1.setRowMargin(2);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 230, 190);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/icon1.jpg"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(30, 10, 901, 213);

        jButton10.setText("Go Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(10, 10, 71, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(460, 160, 240, 260);

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel24.setText("Medicine Name");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 14, 175, 29);

        jTextField3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField3.setText("Enter Medicine Name");
        jPanel5.add(jTextField3);
        jTextField3.setBounds(110, 10, 249, 35);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel25.setText("Price");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 32, 58, 29);

        jTextField4.setText("jTextField4");
        jPanel5.add(jTextField4);
        jTextField4.setBounds(330, 490, 59, 20);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel26.setText("Quantity");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(10, 57, 97, 29);

        jTextField5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField5.setText("Enter medicine price");
        jPanel5.add(jTextField5);
        jTextField5.setBounds(90, 30, 242, 35);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setText("Usage");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(10, 82, 71, 29);

        jTextField6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField6.setText("Enter Quantity");
        jPanel5.add(jTextField6);
        jTextField6.setBounds(100, 50, 171, 35);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel28.setText("Side Effect");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(10, 106, 124, 20);

        jTextField7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField7.setText("Enter Usage");
        jPanel5.add(jTextField7);
        jTextField7.setBounds(100, 80, 145, 35);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel29.setText("Manufacturer");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(10, 140, 152, 29);

        jTextField8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField8.setText("Enter Side Effects");
        jPanel5.add(jTextField8);
        jTextField8.setBounds(100, 110, 211, 35);

        jTextField9.setText("jTextField9");
        jPanel5.add(jTextField9);
        jTextField9.setBounds(103, 310, 59, 20);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel30.setText("Type");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(20, 170, 56, 29);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setText("Salt 1");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(10, 190, 64, 29);

        jTextField10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField10.setText("Enter Manufacturer");
        jPanel5.add(jTextField10);
        jTextField10.setBounds(100, 140, 226, 35);

        jTextField11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField11.setText("Enter Type");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField11);
        jTextField11.setBounds(90, 160, 130, 35);

        jTextField12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField12.setText("Enter Salt");
        jPanel5.add(jTextField12);
        jTextField12.setBounds(90, 180, 118, 35);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("Salt 2");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(10, 210, 64, 29);

        jTextField13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField13.setText("Enter Second Salt(if any)");
        jPanel5.add(jTextField13);
        jTextField13.setBounds(90, 200, 291, 35);

        jButton8.setText("Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(170, 170, 57, 23);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/icon1.jpg"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(40, 0, 901, 213);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(30, 410, 240, 230);

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel33.setText("Enter Medicine Name");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(24, 14, 361, 43);

        jTextField14.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jPanel6.add(jTextField14);
        jTextField14.setBounds(82, 11, 6, 44);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel34.setText("Enter Type");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(35, 52, 186, 43);

        jTextField15.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jPanel6.add(jTextField15);
        jTextField15.setBounds(85, 49, 6, 44);

        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(50, 100, 65, 23);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/icon1.jpg"))); // NOI18N
        jLabel37.setText("jLabel37");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(20, 0, 901, 213);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(340, 20, 160, 130);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/icon1.jpg"))); // NOI18N
        jLabel35.setText("jLabel35");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(190, 20, 901, 213);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1503, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("naman".equals(jTextField1.getText()))
        {
            if("naman".equals(jPasswordField1.getText()))
            {
                jButton1.setVisible(false);
                jTextField1.setVisible(false);
                jPasswordField1.setVisible(false);
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jTextField1.setVisible(false);
               // jPanel2.setVisible(false);
                setSize(1366,768);
//                jPanel3.setVisible(true);
//                jPanel3.setBounds(0, 0, 1366, 768);
                jButton2.setVisible(true);
                jButton2.setBounds(140, 340, 210, 250);
                jButton3.setVisible(true);
                jButton3.setBounds(550, 320, 300, 360);
                
        jButton4.setVisible(true);
        //jButton4.setBounds(560, 20, 210, 250);
                
        jButton4.setVisible(true);
        jButton4.setBounds(1000, 340, 200, 250);
        jLabel35.setBounds(100, 10, 900, 300);
jLabel35.setText(null);
jLabel35.setVisible(true);

        
                
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jPanel2.setVisible(true);
jPanel2.add(jLabel36);
jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
       jLabel36.setBounds(100, 0, 900, 250);
jLabel36.setText(null);
jLabel36.setVisible(true);
        
jPanel2.setBounds(0, 0, 1366, 7687);
jLabel3.setBounds(300, 350, 200, 30);
jTextField2.setBounds(500, 350, 180, 30);
jButton6.setBounds(510, 420, 180, 170);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

jPanel2.setVisible(false);
jPanel4.setVisible(true);
jPanel4.add(jLabel36);
jPanel4.setBounds(0, 0, 1366, 768);
jLabel14.setBounds(200, 70+200, 150, 30);
jLabel15.setBounds(200, 120+200, 200, 30);
jLabel16.setBounds(200, 170+200, 150, 30);
jLabel17.setBounds(200, 220+200, 150, 30);
jLabel18.setBounds(200, 270+200, 150, 30);
jButton10.setBounds(1100, 600, 100, 40);
jTable1.setVisible(false);
jScrollPane1.setBounds(850, 350, 400, 200);
jButton7.setBounds(1100, 100, 190, 290);
String s,s1;
//int count;
s=jTextField2.getText();
access1 a=new access1(s);
a.query();
        ArrayList<String> arst=new ArrayList<>();
        try 
        {
            ResultSetMetaData rsmd=a.rs.getMetaData();
            System.out.println("Result set created");
            int col=rsmd.getColumnCount();
            while(a.rs.next())
            { 
               
                for ( int j = 1; j <= col; j++) 
                {
                    
                  s=a.rs.getString(j);
                  arst.add(s);
                   // System.out.println(s);
                   // s1=a.rs1.getString(j);
                   // System.out.println(s1);
                          

                }
                //count1++;
                
        
        }
            
      jLabel19.setBounds(500, 70+200+5, 150, 30);
      jLabel19.setText(arst.get(0));
jLabel20.setBounds(500, 120+200+5, 200, 30);
jLabel20.setText(arst.get(1));

jLabel21.setBounds(500, 170+200+5, 150, 30);
jLabel21.setText(arst.get(2));
jLabel22.setBounds(500, 220+200+5, 150, 30);
jLabel22.setText(arst.get(3));
jLabel23.setBounds(500, 270+200+5, 150, 30);      
jLabel23.setText(arst.get(4));
            
ResultSetMetaData rsmd1=a.rs1.getMetaData();
            System.out.println("Result set1 created");
             col=rsmd1.getColumnCount();
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
             
            while(a.rs1.next())
            {  arst.clear();
               
                for ( int j = 1; j <= col; j++) 
                {
                    
                  s=a.rs1.getString(j);
                  arst.add(s);
                  
                 //   System.out.println(s);
                   // s1=a.rs1.getString(j);
                   // System.out.println(s1);
                          

                }
                //count1++;
                Object[] row={arst.get(0),arst.get(1)};
                model.addRow(row);
                
        
        }
            jTable1.setVisible(true);
           // jTable1.setLayout(null);
            //jTable1.setBounds(500, 300,jTable1.getWidth(), jTable1.getHeight());
            //tableA.setBounds(5, 35, TablePanel.getWidth() - 15,
             //       TablePanel.getHeight() - 15);
            //jTable1.setBounds(500, 400, 500, 300);
        jLabel36.setBounds(100, 10, 900, 300);
jLabel36.setText(null);
jLabel36.setVisible(true);
            

//Object[] row1={"ja",13};

    //model.addRow(row);
   // model.addRow(row1);
           // jTable1.setLayout(new GridLayout());
            //jTable1.setBounds(600, 400, 500, 300);
           // jTable1.getModel().setValueAt(1, 1, 1);
            //jTable1.getModel().setValueAt(100, 2, 1);
            //jTable1.getModel().setValueAt(220, 1, 0);
            
//jTable1.getModel().setValueAt(row, column, value);
       } catch (Exception e) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        jPanel2.setVisible(false);
        jTextField9.setVisible(false);
        jTextField4.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        
        jPanel5.setVisible(true);
        jPanel5.setBounds(0, 0, 1366, 768);
        jLabel24.setBounds(100, 240, 300, 40);
        jLabel25.setBounds(100, 290, 300, 40);
        jLabel26.setBounds(100, 340, 300,40);
        jLabel27.setBounds(100, 390, 300, 40);
        jLabel28.setBounds(100, 440, 300, 40);
        jLabel29.setBounds(100, 490, 300, 40);
        jLabel30.setBounds(100, 540, 300, 40);
        jLabel31.setBounds(100, 590, 300, 40);
        jLabel32.setBounds(100, 640, 300, 40);
        jTextField3.setBounds(500, 240, 300, 40);
        jTextField5.setBounds(500, 290, 300, 40);
        jTextField6.setBounds(500, 340, 300, 40);
        jTextField7.setBounds(500, 390, 300, 40);
        jTextField8.setBounds(500, 440, 300, 40);
        jTextField10.setBounds(500, 490, 300, 40);
        jTextField11.setBounds(500, 540, 300, 40);
        jTextField12.setBounds(500, 590, 300, 40);
        jTextField13.setBounds(500, 640, 300, 40);
        jButton8.setBounds(900, 600, 81, 40);
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jLabel38.setBounds(70,0, 900, 250);
        try {
            jTextField3.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent fe) {
               jTextField1.setText("");
            }

            @Override
            public void focusLost(FocusEvent fe) {
                //if("".equals(jTextField1.getText()))
                //jTextField1.setText("");
            }
        });
            
            jTextField5.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent fe) {
               jTextField1.setText("");
            }

            @Override
            public void focusLost(FocusEvent fe) {
                //if("".equals(jTextField1.getText()))
                //jTextField1.setText("");
            }
        });
        } catch(Exception e)
        {
            
        }
        
jLabel38.setText(null);
jLabel38.setVisible(true);
        // jTextField12.setBounds(500, 40, 300, 30);
       // jTextField13.setBounds(500, 40, 300, 30);
       // 
//access3 obj=new access3(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
ArrayList<String> arst=new ArrayList<>();
arst.add(jTextField3.getText());// TODO add your handling code here:
arst.add(jTextField5.getText());
       // System.out.println("this jtext "+jTextField4.getText());// TODO add your handling code here:
arst.add(jTextField6.getText());// TODO add your handling code here:
arst.add(jTextField7.getText());// TODO add your handling code here:
arst.add(jTextField8.getText());// TODO add your handling code here:
arst.add(jTextField10.getText());// TODO add your handling code here:
arst.add(jTextField11.getText());// TODO add your handling code here:
arst.add(jTextField12.getText());// TODO add your handling code here:
arst.add(jTextField13.getText());// TODO add your handling code here:
//arst.add(jTextField12.getText());// TODO add your handling code here:
//arst.add(jTextField13.getText());// TODO add your handling code here:
//System.out.println(arst.get(1));
//System.out.println(arst.get(0));
access3 obj=new access3(arst);
obj.query();
int l3=JOptionPane.showConfirmDialog(jPanel6,"Medicine Inserted","Message",JOptionPane.CLOSED_OPTION);
        System.out.println(l3+"naaaaaaaaaaaaaaa");
if(l3==0)
{
    jPanel5.setVisible(false);
    jButton2.setVisible(true);
    jButton3.setVisible(true);
    jButton4.setVisible(true);
    jButton1ActionPerformed(evt);
     
}
  



    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 jLabel33.setVisible(true);
    jTextField14.setVisible(true);
    jTextField14.setText("");
    jButton9.setVisible(true);
        jPanel6.setVisible(true);
jPanel6.setBounds(0, 0, 1366, 768);
jPanel2.setVisible(false);
        jTextField9.setVisible(false);
        jTextField4.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
jLabel33.setBounds(200, 200, 500, 300);
jLabel34.setBounds(200, 400, 500, 300);
jTextField14.setBounds(700, 330, 300, 50);
jTextField15.setBounds(700, 530, 300, 50);
jLabel34.setVisible(false);
jTextField15.setVisible(false);
jButton9.setBounds(1100, 550, 90, 60);
jLabel37.setBounds(100, 10, 900, 300);
jLabel37.setText(null);
jLabel37.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

arst.add(jTextField14.getText());
if(count1>0)           
{this.remove(jp.get(0));
    System.out.println("naman");
}       this.validate();
//arst.clear();
//           ar.clear();
//           jp.clear();
           arst.clear();
           ar.clear();
           jp.clear();
           arst2.clear();
    

 jp.add(new JPanel());
    
         jp.get(0).setLayout(new BoxLayout(jp.get(0),BoxLayout.Y_AXIS));
       jp.get(0).setBounds(0,400,1366,768);
       jp.get(0).setBackground(jPanel6.getBackground());
       this.add(jp.get(0));
         jp.get(0).setVisible(true);
         int ini;
//arst.add(jTextField15.getText());
access obj21= new access(jTextField14.getText());
        obj21.query();
        try {
             ResultSetMetaData rsmd = obj21.rs.getMetaData();
            System.out.println("Result set Created");
            
            
                       String s="";
            int col=rsmd.getColumnCount();
            
            while(obj21.rs.next())
            { 
               
                for ( int j = 1; j <= col; j++) 
                 {
                    if(j==1)
                    { s = obj21.rs.getString(j);
                    arst.add(s);}
                     if(j==2)
                    {
                     ini=obj21.rs.getInt(j);
                      arst2.add(ini);
                       // System.out.println("nkaskfs"+ini);
                    }            //      jTextField1.setText(s);

                }
                count1++;
                
        
        }
              for (int j = 0; j < count1; j++) {
                ar.add(new JButton(arst.get(j)));
                ar.get(j).setBackground(Color.WHITE);
             //  ar.get(j).setBounds(10, 20+10, 30, 30);
                jp.get(0).add(ar.get(j));

            }
            jp.get(0).validate();
            for (int k = 0; k < count1; k++) 
             {
                 //count2=k;
                 //System.out.println("in first for loop"+k);
             ar.get(k).addActionListener(new ActionListener() {

                 @Override
                 
                 public void actionPerformed(ActionEvent e) 
                 {
                    

                         //@Override
                    //     public void run() {
                              for(int l=0;l<count1;l++)
                              
                             {
                               //   System.out.println("in for loop"+l);
                              if(e.getSource()==ar.get(l))
                              {   //System.out.println("kdksd"); 
                   //               System.out.println(arst.get(l)+"naman");
                            //  access15 obj2 = new  access15(arst2.get(l));
                                 //   obj2.query();
                                
 
 {int l2=JOptionPane.showConfirmDialog(jPanel6,"Delete Medicine?");
 if(l2==JOptionPane.YES_OPTION)
 {//jButton1ActionPerformed(e);
     access4 o=new access4(arst.get(l));
     System.out.println("okkk");
int m=o.query();
int l3=JOptionPane.showConfirmDialog(jPanel6,"Medicine Deleted","Message",JOptionPane.CLOSED_OPTION);
     System.out.println(l3);
if(l3==0)
{
    jLabel33.setVisible(false);
    jTextField14.setVisible(false);
    jButton9.setVisible(false);
    jp.get(0).setVisible(false);
    jButton2.setVisible(true);
    jButton3.setVisible(true);
    jButton4.setVisible(true);
    
    jButton1ActionPerformed(e);
}
    
 }
 }        //else
       // jButton4ActionPerformed(evt);
                                 // System.out.println(m);
//                                
                     //               System.out.println("vsdsfssf");
                                 // new medicine_1(obj2.rs,obj2.rs1).setVisible(true);
                              }
                                  }   
                             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                         }
                   
                  
               }
            );
       }
            System.out.println("hello");
               //jp.get(0).setBounds(1101,201,200,400);
            

        } catch (Exception e) {
        }

//access4 0=new access4(arst);
//access4 o=new access4(arst);
//o.query();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        jPanel4.setVisible(false);
        jButton2.setVisible(true);
    jButton3.setVisible(true);
    jButton4.setVisible(true);
    jButton1ActionPerformed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void log() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    //class mytablemodel extends Jtable

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
