/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medikart;

import java.awt.Button;
import java.awt.GridLayout;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author naman
 */
public class medical extends javax.swing.JFrame {

    /**
     * Creates new form medical
     */
     String st;
      ArrayList<JButton> ar = new ArrayList<>();
    ArrayList<String> arst=new ArrayList<>();
    int count1=0;
    ArrayList<JPanel> jp= new ArrayList<>();
    public medical() {

        initComponents();
        jPanel3.setVisible(false);
        
        setSize(1366, 768);
        jButton1.setBounds(100, 250, 250, 390);
        jButton3.setBounds(400, 250, 250, 390);
        jTextPane1.setBounds(700, 250, 250, 390);
        jButton2.setBounds(1000, 250, 240, 390);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        try {
            jTextField1.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent fe) {
               jTextField1.setText("");
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if("".equals(jTextField1.getText()))
                jTextField1.setText("Search");
            }
        });
        } catch (Exception e) {
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/1.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(57, 290, 245, 392);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/1.jpg"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(379, 290, 242, 392);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(153, 255, 153));
        jTextPane1.setText("Search for a medicine,\nget all the important\ninformation related to it\nand then, buy it online\n\n\n\nAll of this from this \nsimple App\n");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(692, 317, 218, 315);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setLayout(null);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(30, 30, 200, 40);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(240, 30, 73, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1249, 0, 0, 770);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/2.jpg"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(980, 260, 238, 392);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jButton2.setVisible(false);
      
        jPanel3.setVisible(true);
        jPanel3.setBounds(1000, 0, 1366, 768);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        if("".equals(jTextField1.getText()))
            JOptionPane.showMessageDialog(this,"Enter a Valid Name");
          else
        jButton4ActionPerformed(evt);
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(count1>0)           
        jPanel3.remove(jp.get(0));

        arst.clear();
           ar.clear();
           jp.clear();
    
           st=jTextField1.getText(); 
        
count1=0;



access obj= new access(st);
        obj.query();
        try {
            
        
 
        ResultSetMetaData rsmd = obj.rs.getMetaData();
            System.out.println("Result set Created");
            
            
                       String s="";
            int col=rsmd.getColumnCount();
            
            
           

    jPanel3.setLayout(null);
            jp.add(new JPanel());
    
         jp.get(0).setLayout(new BoxLayout(jp.get(0),BoxLayout.Y_AXIS));
       jp.get(0).setBounds(0,300,400,800);
       jp.get(0).setBackground(jPanel3.getBackground());
       jPanel3.add(jp.get(0));
         jp.get(0).setVisible(true);
        //jp.get(0).setBounds(0, 50, 150, 150);
            while(obj.rs.next())
            { 
               
                for ( int j = 1; j <= col; j++) 
                {
                    
                  s=obj.rs.getString(j);
                  arst.add(s);
                          

                }
                count1++;
                
        
        }
//            System.out.println("heello yhi sts count"+count1);
//            for (int j = 0; j < count1; j++) 
//            {
//                System.out.println(arst.get(j));    
//            }
//            
  //          System.out.println(count1);
           for (int j = 0; j <count1; j++) 
       {
           ar.add(new JButton(arst.get(j)));
           ar.get(j).setBounds(1320,200,30,30);
           jp.get(0).add(ar.get(j));
           
      
       }
           jp.get(0).validate();
           System.out.println("he;llooo");

    
            } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
login lg=new login();
lg.log();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
