/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medikart;

import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author Jaspreet Singh
 */
public class medicine_1 extends javax.swing.JFrame {

    /**
     * Creates new form medicine
     */
    ResultSet rs1, rs3;
    String st = "";
    String name;
    int a, b, n,mid;
    JFrame jf;

    public medicine_1(ResultSet rs, ResultSet rs2,JFrame jf) {
        //int a=id;
        rs1 = rs;
        rs3 = rs2;

        initComponents();
        setSize(1366, 768);
        jPanel1.setBounds(0, 0, 1366, 768);
        jLabel1.setBounds(200, 50, 350, 50);
        jPanel1.setLayout(null);

        jScrollPane1.setBounds(200, 100, 200, 60);
        jButton1.setVisible(false);
        //jButton2.setVisible(true);
       
        jScrollPane2.setBounds(200, 250, 350, 100);
        jLabel2.setBounds(200, 200, 350, 50);
        //jTextPane2.setFont;
        jLabel2.setText("Composition");
        jLabel3.setBounds(200, 350, 350, 50);
        jScrollPane3.setBounds(200, 400, 350, 120);
        jLabel3.setText("Typical Usage:");

        jLabel4.setBounds(200, 570, 350, 50);
        jLabel4.setText("Side Effects:");
        jScrollPane4.setBounds(200, 620, 350, 740);

        jScrollPane5.setBounds(550, 100, 200, 200);
        jTextPane5.setText("Manufacturer:");

        jPanel1.add(jComboBox1);
        jPanel1.add(jButton2);
         jButton2.setBounds(396, 100, 150, 60);
        jButton2.setText("BUY");
        jComboBox1.setBounds(550, 400, 200, 100);
        jButton2.setVisible(true);
        this.jf=jf;
        jButton3.setBounds(20,20 ,100 ,100);
        jPanel1.add(jButton3);
        validate();
        fun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(62, 11, 124, 43);

        jTextPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(62, 66, 90, 30);

        jScrollPane2.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(62, 115, 90, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 70, 105, 31);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 80, 29);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 160, 60, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 50, 29);

        jTextPane3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jScrollPane3.setViewportView(jTextPane3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(70, 170, 50, 30);

        jTextPane4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jScrollPane4.setViewportView(jTextPane4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(70, 210, 30, 30);

        jTextPane5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jScrollPane5.setViewportView(jTextPane5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(260, 160, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(70, 70, 160, 100);

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 150, 131, 37);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/images.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 20, 237, 213);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        n = Integer.parseInt(jComboBox1.getSelectedItem().toString());
                    b = n * a;

        System.out.println(n);
        System.out.println("hkdshfkdslfsdkhf djkadjas");
        this.setVisible(false);
        bill bi = new bill(a,b,n,name,mid,jf);
        bi.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jf.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new medicine().setVisible(true);
//            }
//        });
    void fun() {
        try {
//                                      obj1.rs.next();
//                   System.out.println("jdasjdksadjasdk"+obj1.rs.getString(1));
            while (rs3.next()) {

                st = st + rs3.getString(1) + "\n";
            }
            jTextPane2.setText(st);

            while (rs1.next()) {
                mid = rs1.getInt("medicine_id");
                name=rs1.getString("Medicine_Name");
                jLabel1.setText(name);
               // System.out.println("before mrp");
                jTextPane1.setText("MRP..." + "\n"+rs1.getString("Price"));
               // System.out.println("after mrp");
                a = Integer.parseInt(rs1.getString("Price"));
                jTextPane3.setText( rs1.getString("Usage"));
               // System.out.println("after after mrp");
                jTextPane4.setText(rs1.getString("Side_Effect"));
                jTextPane5.setText("Manufacturer:" + "\n\n" + rs1.getString("Manufacturer"));
                //System.out.println("Hello_value" + a);

            }


        } catch (Exception ex) {
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
}
