/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medikart;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Karan
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
      String  st,st1,st2,st3;;
         int i,j; 
     ArrayList<JButton> ar = new ArrayList<>();
    ArrayList<String> arst = new ArrayList<>();
    int count1 = 0;
    ArrayList<JPanel> jp = new ArrayList<>();
               ArrayList<Integer> arst2 = new ArrayList<>();

    int count2=0;
    
         
    JFrame jthis,jthis2;
    public search(JFrame jf) {
      
        initComponents();
      //  getContentPane().setBackground(Color.White);
       // JFrame.getContentPane().setBackground(Color.White);
        setSize(1366, 768);
        jLabel2.setBounds(400,50, 400, 50);
        jLabel3.setBounds(50, 170, 200, 50);
        medicine.setBounds(250, 170, 400, 50);
        jLabel5.setBounds(50,270 , 200, 50);
        Price1.setBounds(250, 270, 100, 50);
        Price2.setBounds(500, 270, 100, 50);
        jLabel6.setBounds(400, 270, 50, 50);
        jLabel7.setBounds(50, 370, 200, 50);
        type.setBounds(250, 370, 200, 50);
       // jButton1.setBounds(450, 470, 200, 50);
        jPanel1.setBounds(0, 0, 1366, 768);
        image.setBounds(850, 200, 325, 400);
       jthis2=jf;
jthis=this;       
// image.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        medicine = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        image = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Price1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Price2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextField2.setText("jTextField2");

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 107, 59, 0);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Advance Search");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 20, 580, 100);

        medicine.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(medicine);
        medicine.setBounds(240, 180, 320, 35);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Medicine_Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 170, 88, 35);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/download (1).jpg"))); // NOI18N
        image.setText("jButton2");
        image.setToolTipText("");
        image.setFocusPainted(false);
        image.setFocusable(false);
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });
        image.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                imageFocusLost(evt);
            }
        });
        jPanel1.add(image);
        image.setBounds(480, 280, 80, 100);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("Price:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 110, 50);

        Price1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Price1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "20", "40", "60","80","100" }));
        Price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price1ActionPerformed(evt);
            }
        });
        jPanel1.add(Price1);
        Price1.setBounds(250, 260, 38, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("TO");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 250, 30, 32);

        Price2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Price2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "40", "60", "80","100","120" }));
        Price2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price2ActionPerformed(evt);
            }
        });
        jPanel1.add(Price2);
        Price2.setBounds(440, 260, 38, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Type:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 370, 90, 50);

        type.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tablet", "Capsule", "Syrup", "Cream","Inhaler","Injection","Eye drop","Ear drop" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type);
        type.setBounds(140, 380, 93, 28);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medikart/images.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 20, 90, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, -4, 650, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
    
    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_typeActionPerformed

    private void Price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price1ActionPerformed

    private void imageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imageFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_imageFocusLost

    private void Price2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price2ActionPerformed

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        // TODO add your handling code here:
         st=medicine.getText();
         if("".equals(st))
             JOptionPane.showMessageDialog(this,"Enter Valid Medicine Name","Invalid Search",JOptionPane.INFORMATION_MESSAGE);
          else
         {       
        st1=Price1.getSelectedItem().toString();
        st2=Price2.getSelectedItem().toString();
        st3=type.getSelectedItem().toString();

       i=Integer.parseInt(st1);
       j=Integer.parseInt(st2);
        System.out.println(i);
        System.out.println(st);
        System.out.println(st3);
       
        if(count1>0)           
        jPanel1.remove(jp.get(0));
        jPanel1.validate();
        arst.clear();
           ar.clear();
           jp.clear();
           arst2.clear();
    
           //st=jTextField1.getText(); 
        
      count1=0;
      
        access2 obj= new access2(st,i,j,st3);
        obj.query();
        
        try {
            
        
           // output.setText("");
        ResultSetMetaData rsmd = obj.rs.getMetaData();
        System.out.println("Result set Created");
            
    
                       String s="";
                   
                       
            int col=rsmd.getColumnCount();
            
            
           
//jPanel1.setLayout(new BoxLayout(jPanel1,BoxLayout.Y_AXIS));

    //jPanel3.setLayout(null);
        jp.add(new JPanel());
    
     jp.get(0).setLayout(new BoxLayout(jp.get(0),BoxLayout.Y_AXIS));
       jp.get(0).setBounds(70,600,300,300);
       jp.get(0).setBackground(jPanel1.getBackground());
      jPanel1.add(jp.get(0));
         jp.get(0).setVisible(true);
        //jp.get(0).setBounds(0, 50, 150, 150);
         int ini;  
         while(obj.rs.next())
            { 
               
                for ( int j = 1; j <= 2; j++) 
                {
                    
                 if(j==1)
                 {s=obj.rs.getString(j);
                  arst.add(s);
                    System.out.println(s);}
                    if(j==2)
                    {
                    ini=obj.rs.getInt(j);
                  arst2.add(ini);
                    }               // output.setText(s);
                          

                }
                count1++;
                
        
        }
       //     System.out.println(" count is:"+count1);
         //   for (int j = 0; j < count1; j++) 
//            {
//                //System.out.println(arst.get(j));    
//            }
            
            //System.out.println(count1);
           for (int j = 0; j <count1; j++) 
       {
           ar.add(new JButton(arst.get(j)));
          ar.get(j).setBounds(10,20,30,30);
           jp.get(0).add(ar.get(j));
           
      
       }
           jp.get(0).validate();
                    //jp.get(0).setBounds(100,500,400,800);

           System.out.println("he;llooo");
               //jp.get(0).setBounds(1101,201,200,400);
           //obj.rs.first();
           
            System.out.println("hi");
//           while(obj.rs.next())
//           {
//               for ( int j = 2; j <= 2; j++) 
//                {
//                    
//                  
//                  //  System.out.println(s);
//                                    // output.setText(s);
//                          
//
//                }
//           }
            
             for (int k = 0; k < count1; k++) 
             {
                 //count2=k;
                 System.out.println("in first for loop"+k);
             ar.get(k).addActionListener(new ActionListener() {

                 @Override
                 
                 public void actionPerformed(ActionEvent e) 
                 {
                    

                         //@Override
                    //     public void run() {
                              for(int l=0;l<count1;l++)
                              
                             {
                               //   System.out.println("in for loop"+l);
                              if(e.getSource()==ar.get(l))
                              {     access15 obj1 = new  access15(arst2.get(l));
                              obj1.query();
//                                  try {
////                                      obj1.rs.next();
////                                      System.out.println("jdasjdksadjasdk"+obj1.rs.getString(1));
//                                         while(obj1.rs.next())
//            {
//                System.out.println(obj1.rs.getInt("medicine_id"));
//            
//            }
//         
//
//                                  } catch (Exception ex) {
//                                  }
//                                          jth
                              jthis.setVisible(false);
                                  new medicine_1(obj1.rs,obj1.rs1,jthis).setVisible(true);
                              }
                                  }   
                       //      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                         }
                   
                     
                 }
             );
        }
                     System.out.println("hello after loop");

             
    
            } catch (Exception e) {
        }
         }
    }//GEN-LAST:event_imageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jthis.setVisible(false);
        jthis2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
// public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new search().setVisible(true);
//         }
//        });
//    };
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Price1;
    private javax.swing.JComboBox Price2;
    private javax.swing.JButton image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField medicine;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
